[package]
name = "tygres-macros"
version = "0.1.0"
authors = ["Rajsekar Manokaran <rajsekar@gmail.com>"]
edition = "2018"

[dependencies]
syn = "0.15.17"
quote = "0.6.9"
proc-macro2 = "0.4.20"
inflections = "1.1.1"
darling = "0.8.0"

[lib]
proc-macro = true
